const typeFolders = {
  svg: "Images",
  jpg: "Images",
  png: "Images",
  jpeg: "Images",
  webp: "Images",
  tiff: "Images",
  tif: "Images",
  psd: "Images",
  heif: "Images",
  exe: "Applications",
  msi: "Applications",
  xlsx: "Documents",
  pdf: "Documents",
  docx: "Documents",
  ppt: "Documents",
  pptx: "Documents",
  xlsx: "Documents",
  doc: "Documents",
  xls: "Documents",
  csv: "Documents",
  rtf: "Documents",
  zip: "Compressed",
  rar: "Compressed",
  "7z": "Compressed",
  mkv: "Videos",
  mp4: "Videos",
  avi: "Videos",
  mov: "Videos",
  webm: "Videos",
  flv: "Videos",
  "3gp": "Videos",
  vob: "Videos",
  mp3: "Music",
  flac: "Music",
  aac: "Music",
  ogg: "Music",
  m4a: "Music",
  wma: "Music",
};

module.exports = typeFolders;
